### PR TITLE
Deprecate old CV interface for openCV3

### PR DESCRIPTION
**Pull request by christianjgreen**
This PR is directed towards issue #15

openCV 3.x dropped the deprecated C API interface cv for the currently maintained C++ interface cv2.

A new engine was created using cv2 and numpy to support ongoing openCV development.

### CODE REVIEW

**Comment by Arthien** [comment]
@scorphus @savar @seffenberg-naspers @ustav2307
How's this? :)

**Comment by Savar** [comment]
:D fine for me.. @anyone who is an owner here.. can we get this through?

Am 23. Dezember 2017 02:26:18 MEZ schrieb Christian Green <notifications@github.com>:
>@scorphus @savar @seffenberg-naspers @ustav2307
>How's this? :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/opencv-engine/pull/32#issuecomment-353698749

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Savar** [comment]
@heynemann @scorphus ?

**Comment by Savar** [comment]
@Arthien maybe interesting for you and should be probably in this pull request as well:

https://github.com/naspersclassifieds-regional/coreservices-opencv-engine/commit/843f919fd846a3049b6a866d38a6b2e10efaa2b2

**Comment by bagipriyank** [comment]
any update on this?

**Comment by heynemann** [comment]
Sorry for the delay. I'm not actually working with the opencv-engine. We are in dire need of maintainers.

**Comment by christianjgreen** [comment]
I'm still here!

**Comment by heynemann** [comment]
Do you wish to become a maintainer for opencv-engine?

**Comment by christianjgreen** [comment]
@heynemann I'd enjoy that thank you. Also looking at making a libvips engine for thumbor.

**Comment by Enalmada** [comment]
Awesome.  BTW I noticed that an article about [imgproxy](https://evilmartians.com/chronicles/introducing-imgproxy) labeled vips as an advantage over thumbor so it would be interesting to get thumbor using it too.

**Comment by heynemann** [comment]
"Cutting extra features and focusing on core functionality allows for a very lightweight and memory-efficient solution. Thumbor, for instance, is very powerful, but its Docker container is 300 times bigger than imgproxy’s. It also does not support 12factor and uses GraphicsMagick as an underlying library, which is considerably slower than vips."

This is just plain lying, lol. Thumbor does follow 12 factor. You run it with `thumbor`, you pass port and configuration file to it. EVERY single part of thumbor is extensible. 

I hate when developers resort to trickery to promote their thing. :(

**Comment by heynemann** [comment]
@Arthien just added you as a committer! Welcome aboard! Looking forward to your libvips engine!

**Comment by heynemann** [comment]
Thanks for the pointer @Enalmada. I asked for some corrections in the article you pointed to at https://github.com/DarthSim/imgproxy/issues/58

Hope Sergey does update his article! Anyways, I hope more open source options do appear. The diversity in the imaging ecosystem improves all the options and is beneficial to all devs.

**Comment by savar** [comment]
Me too! @arthien did you already compare somehow libvips with opencv? Or is there a good article about it?

Am 24. Mai 2018 02:04:13 MESZ schrieb Bernardo Heynemann <notifications@github.com>:
>@Arthien just added you as a committer! Welcome aboard! Looking forward
>to your libvips engine!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/opencv-engine/pull/32#issuecomment-391541846

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Pull request merged**
